apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-shipping-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi